name: Model Training

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    permissions: write-all

    runs-on: self-hosted
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v3
      - name: Try comment
        run: |
          cml comment update --target=pr --token ${{ secrets.GITHUB_TOKEN }} README.md