name: Model Training

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Set up gcloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.FRDC_DOWNLOAD_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      #     We don't necessarily need to install the CUDA version of torch, so we'll do with cpu
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest poetry          
          poetry export --with dev --without-hashes -o requirements.txt
          pip install -r requirements.txt
          pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

      - name: Test with pytest
        run: |
          pytest tests/model_tests


